name: Benchmarks
on: 
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled ]
  workflow_dispatch: 


jobs:
  libor:
    if: contains(github.event.pull_request.labels.*.name, 'benchmarks') || github.event_name == 'workflow_dispatch'
    name: Libor Swaption Sample
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/foonathan/gcc:12
    outputs:
      libor: ${{ steps.libor-results.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: benchmark-libor
      - name: configure
        run: |
          mkdir build
          cd build
          cmake .. -GNinja \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=g++ \
            -DXAD_NO_THREADLOCAL=ON \
            -DXAD_SIMD_OPTION=AVX2 \
            -DXAD_USE_STRONG_INLINE=ON
      - name: build
        run: |
          cd build
          cmake --build .
      - name: Run Test
        run: |
          cd build
          ctest --no-compress-output --output-on-failure --parallel $(($(nproc) + 2))
      # if we are on main branch & triggered by workflow-dispatch, push artefact
      - name: Push Reference
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: libor_exe
          path: build/samples/LiborSwaptionPricer/LiborSwaptionPricer
          if-no-files-found: error
          retention-days: 90
          overwrite: true
      # if we are in a pull request, pull the uploaded artifact from earlier and run
      - name: Pull Reference
        uses: actions/download-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: libor_exe
          repository: auto-differentiation-dev/xad
          path: build/samples/LiborSwaptionPricer/ref
          github-token: ${{ secrets.WORKFLOW_READ_TOKEN }}
          run-id: 11161385127
      - name: Run Reference
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd build/samples/LiborSwaptionPricer/ref
          ls -l
          file ./LiborSwaptionPricer
          chmod +x ./LiborSwaptionPricer
          ./LiborSwaptionPricer 100000 | tee ../reference.log
          ./LiborSwaptionPricer 100000 | tee -a ../reference.log
          ./LiborSwaptionPricer 100000 | tee -a ../reference.log
          ./LiborSwaptionPricer 100000 | tee -a ../reference.log
          ./LiborSwaptionPricer 100000 | tee -a ../reference.log
      - name: Run Benchmark
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd build/samples/LiborSwaptionPricer
          ./LiborSwaptionPricer 100000 | tee output.log
          ./LiborSwaptionPricer 100000 | tee -a output.log
          ./LiborSwaptionPricer 100000 | tee -a output.log
          ./LiborSwaptionPricer 100000 | tee -a output.log
          ./LiborSwaptionPricer 100000 | tee -a output.log
      - name: Prepare results
        if: github.event_name == 'pull_request'
        id: libor-results
        run: |
          set -e
          apt-get update && apt-get install -y bc
          OUT_TIME=$(awk 'BEGIN { best=100000.0 } $2 == "AAD" { best = best < $4 ? best : $4; } END {print best}' build/samples/LiborSwaptionPricer/output.log)
          echo "Run time: $OUT_TIME"
          REF_TIME=$(awk 'BEGIN { best=100000.0 } $2 == "AAD" { best = best < $4 ? best : $4; } END {print best}' build/samples/LiborSwaptionPricer/reference.log)
          echo "Reference time: $REF_TIME"
          DIFFERENCE=$(echo "scale=9; $REF_TIME - $OUT_TIME" | bc | awk '{printf "%.3f\n", $1}')
          echo "Difference: $DIFFERENCE"
          PERCENTAGE=$(echo "scale=9; (($REF_TIME - $OUT_TIME) / $REF_TIME) * 100.0" | bc | awk '{printf "%.3f\n", $1}')
          echo "Percentage: $PERCENTAGE"
          
          echo "result=| ${REF_TIME}s | ${OUT_TIME}s | ${PERCENTAGE}% |" >> "$GITHUB_OUTPUT"
      
  quantlib:
    if: contains(github.event.pull_request.labels.*.name, 'benchmarks') || github.event_name == 'workflow_dispatch'
    name: QuantLib Samples
    runs-on: ubuntu-latest
    container: ghcr.io/lballabio/quantlib-devenv:noble-1.85.0
    outputs:
      test: ${{ steps.test-results.outputs.result }}
      bermudan: ${{ steps.bermudan-results.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: xad
      - uses: actions/checkout@v4
        with:
          repository: lballabio/QuantLib
          ref: v1.35
          path: QuantLib
      - uses: actions/checkout@v4
        with:
          path: QuantLib-Risks-Cpp
          repository: auto-differentiation/QuantLib-Risks-Cpp
          ref: a1fcf4f0fab0a464710c249aa76871421675babd
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: benchmark-quantlib
      - name: Setup
        run: |
          apt-get update \
          && apt-get install -y ninja-build bc
      - name: Configure
        run: |
          cd QuantLib
          mkdir build
          cd build
          cmake -G Ninja -DBOOST_ROOT=/usr \
            -DCMAKE_CXX_STANDARD=17 \
            -DQLRISKS_DISABLE_AAD=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DQL_EXTERNAL_SUBDIRECTORIES="$(pwd)/../../xad;$(pwd)/../../QuantLib-Risks-Cpp" \
            -DQL_EXTRA_LINK_LIBRARIES=QuantLib-Risks \
            -DQL_NULL_AS_FUNCTIONS=ON \
            -DXAD_NO_THREADLOCAL=ON \
            -DXAD_SIMD_OPTION=AVX2 \
            ..
      - name: Compile
        run: |
          cd QuantLib/build
          cmake --build .
      - name: Test QuantLib
        if: github.event_name == 'pull_request'
        run: |
          cd QuantLib/build
          ./test-suite/quantlib-test-suite --log_level=message    
      - name: Test QuantLib-Risks
        if: github.event_name == 'pull_request'
        run: |
          cd QuantLib/build
          ./QuantLib-Risks-Cpp/test-suite/quantlib-risks-test-suite --log_level=message
      # if we are on main branch & triggered by workflow-dispatch, push artefact
      - name: Push Reference Test-suite
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: ql_test_exe
          path: QuantLib/build/test-suite/quantlib-test-suite
          if-no-files-found: error
          retention-days: 90
          overwrite: true
      - name: Push Reference AdjointBermudan
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: ql_bermudan_exe
          path: QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption/AdjointBermudanSwaption
          if-no-files-found: error
          retention-days: 90
          overwrite: true
      # if we are in a pull request, pull the uploaded artifact from earlier and run
      - name: Pull Reference Test-suite
        uses: actions/download-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: ql_test_exe
          repository: auto-differentiation-dev/xad
          path: QuantLib/build/test-suite/ref
          github-token: ${{ secrets.WORKFLOW_READ_TOKEN }}
          run-id: 11161385127
      - name: Pull Reference AdjointBermudan
        uses: actions/download-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: ql_bermudan_exe
          repository: auto-differentiation-dev/xad
          path: QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption/ref
          github-token: ${{ secrets.WORKFLOW_READ_TOKEN }}
          run-id: 11161385127
      - name: Run Reference Test-suite
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd QuantLib/build/test-suite/ref
          ls -l
          file ./quantlib-test-suite
          chmod +x ./quantlib-test-suite
          ./quantlib-test-suite --log_level=test_suite --run_test="QuantLibTests/*/testPathwiseGreeks" | grep -v "is skipped because" | tee ../reference.log
          for i in $(seq 1 9) ; do \
            ./quantlib-test-suite --log_level=test_suite --run_test="QuantLibTests/*/testPathwiseGreeks" | grep -v "is skipped because" | tee -a ../reference.log ; \
          done
      - name: Run Benchmark Test-suite
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd QuantLib/build/test-suite
          ./quantlib-test-suite --log_level=test_suite --run_test="QuantLibTests/*/testPathwiseGreeks" | grep -v "is skipped because" | tee output.log
          for i in $(seq 1 9) ; do \
            ./quantlib-test-suite --log_level=test_suite --run_test="QuantLibTests/*/testPathwiseGreeks" | grep -v "is skipped because" | tee -a output.log ; \
          done
      - name: Prepare results Tests-suite
        if: github.event_name == 'pull_request'
        id: test-results
        run: |
          set -e
          
          OUT_TIME=$(sed -e 's/us$//g' QuantLib/build/test-suite/output.log | \
                     awk 'BEGIN { best=1000000000 } \
                          $0 ~ /Leaving test case.*testPathwiseGreeks/ { best = best < $NF ? best : $NF; } \
                          END {printf "%.3f\n", best / 1000}' )
          echo "Run time: $OUT_TIME"
          REF_TIME=$(sed -e 's/us$//g' QuantLib/build/test-suite/reference.log | \
                     awk 'BEGIN { best=1000000000 } \
                     $0 ~ /Leaving test case.*testPathwiseGreeks/ { best = best < $NF ? best : $NF; } \
                     END {printf "%.3f\n", best / 1000}' )
          echo "Reference time: $REF_TIME"
          DIFFERENCE=$(echo "scale=9; $REF_TIME - $OUT_TIME" | bc | awk '{printf "%.3f\n", $1}')
          echo "Difference: $DIFFERENCE"
          PERCENTAGE=$(echo "scale=9; (($REF_TIME - $OUT_TIME) / $REF_TIME) * 100.0" | bc | awk '{printf "%.3f\n", $1}')
          echo "Percentage: $PERCENTAGE"
          
          echo "result=| ${REF_TIME}ms | ${OUT_TIME}ms | ${PERCENTAGE}% |" >> "$GITHUB_OUTPUT"
          
      - name: Run Reference AdjointBermudan
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption/ref
          ls -l
          file ./AdjointBermudanSwaption
          chmod +x ./AdjointBermudanSwaption
          ./AdjointBermudanSwaption 500 | tee ../reference.log
          ./AdjointBermudanSwaption 500 | tee -a ../reference.log
          ./AdjointBermudanSwaption 500 | tee -a ../reference.log
          ./AdjointBermudanSwaption 500 | tee -a ../reference.log
      - name: Run Benchmark AdjointBermudan
        if: github.event_name == 'pull_request'
        run: |
          set -e
          cd QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption
          ./AdjointBermudanSwaption 500 | tee output.log
          ./AdjointBermudanSwaption 500 | tee -a output.log
          ./AdjointBermudanSwaption 500 | tee -a output.log
          ./AdjointBermudanSwaption 500 | tee -a output.log
      - name: Prepare results Bermudan
        if: github.event_name == 'pull_request'
        id: bermudan-results
        run: |
          set -e
          
          OUT_TIME=$( awk 'BEGIN { best=1000000.0 } \
                          $1 == "For" && $7 == "average" { best = best < $8 ? best : $8; } \
                          END {printf "%.3f", best}' \
                          QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption/output.log)
          echo "Run time: $OUT_TIME"
          REF_TIME=$( awk 'BEGIN { best=1000000.0 } \
                          $1 == "For" && $7 == "average" { best = best < $8 ? best : $8; } \
                          END {printf "%.3f", best}' \
                          QuantLib/build/QuantLib-Risks-Cpp/Examples/AdjointBermudanSwaption/reference.log)
          echo "Reference time: $REF_TIME"
          DIFFERENCE=$(echo "scale=9; $REF_TIME - $OUT_TIME" | bc | awk '{printf "%.3f\n", $1}')
          echo "Difference: $DIFFERENCE"
          PERCENTAGE=$(echo "scale=9; (($REF_TIME - $OUT_TIME) / $REF_TIME) * 100.0" | bc | awk '{printf "%.3f\n", $1}')
          echo "Percentage: $PERCENTAGE"
          
          echo "result=| ${REF_TIME}ms | ${OUT_TIME}ms | ${PERCENTAGE}% |" >> "$GITHUB_OUTPUT"


  collect:
    name: Collect Results
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs:
      - quantlib
      - libor
    env:
      LIBOR: ${{ needs.libor.outputs.libor }}
      TESTSUITE: ${{ needs.quantlib.outputs.test }}
      BERMUDAN: ${{ needs.quantlib.outputs.bermudan }}
    steps:
      - name: Collect results into markdown
        run: |
          echo "## Performance Results" > results.md
          echo "" >> results.md
          echo "Best of the given executions, with pre-built reference and this PR's version." >> results.md
          echo "" >> results.md
          echo "| Application | Executions | Reference | Result | Improvement |" >> results.md
          echo "|-------------|-----------:|----------:|-------:|------------:|" >> results.md
          echo "| [LIBOR Swaption (100K paths)](https://github.com/auto-differentiation/xad/tree/main/samples/LiborSwaptionPricer) | 5 $LIBOR" >> results.md
          echo "| [testPathwiseGreeks](https://github.com/lballabio/QuantLib/blob/v1.35/test-suite/marketmodel.cpp#L2090) | 10 $TESTSUITE" >> results.md
          echo "| [Bermudan Swaption (500 repetitions)](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/blob/main/Examples/AdjointBermudanSwaption/AdjointBermudanSwaptionXAD.cpp) | 5 $BERMUDAN" >> results.md

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Performance Results
      - name: Post or update PR comment
        id: pr-comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: results.md
          edit-mode: replace